# Generated by Django 5.0.3 on 2024-03-12 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookinstance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='book_genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(help_text='Enter your book name ', on_delete=django.db.models.deletion.DO_NOTHING, to='bookinstance.book')),
                ('genre', models.ForeignKey(help_text='Enter your genre', on_delete=django.db.models.deletion.DO_NOTHING, to='bookinstance.genre')),
            ],
        ),
    ]
