# Generated by Django 5.0.3 on 2024-03-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookinstance", "0004_bookinstance_borrower"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookinstance",
            name="status",
            field=models.CharField(
                choices=[("a", "Available"), ("b", "Borrowed"), ("r", "Reserved")],
                help_text="Book availability",
                max_length=1,
            ),
        ),
    ]
