# Generated by Django 5.0.3 on 2024-03-21 11:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookinstance", "0005_alter_bookinstance_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookinstance",
            options={
                "ordering": ["status"],
                "permissions": (("normal", "Normal"), ("vip", "Vip")),
            },
        ),
    ]
